### ISSUE TITLE
fib(2) should be 1

### ISSUE THREAD

**Issue by drodsou** [dominictarr/fib.wasm#1]
Hi, as this is the first result in google searching `fib.wasm` I thought it was worth opening the issue:

There is a shift in the results: fib(2) shoud be 1

https://math.hmc.edu/funfacts/fibonacci-number-formula/

Regards

**Comment by dominictarr** [comment]
haha, thanks. I'm sure no one really needs to actually run this it's just example code.

fixed it anyway.

as you'll have seen, hand writing wat can be quite cumbersome (although very educational) but if that interests you, you may care to look at my new project: https://github.com/dominictarr/acidlisp/

it's a lisp that compiles directly to wat, so that you can get low level performance like writing wat by hand, but without it being so verbose.

**Comment by dominictarr** [comment]
fixed in 1.0.2
